# Generated by Django 5.0.3 on 2024-03-11 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_hastag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hastag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hastag')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_hastags', to='core.post')),
            ],
        ),
    ]
