# Generated by Django 5.0.3 on 2024-03-12 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_hastag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
