# Generated by Django 5.0.3 on 2024-03-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_name_alter_profile_bio_alter_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
