# Generated by Django 5.0.3 on 2024-03-19 00:03

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_post_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no_of_like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
