# Generated by Django 5.0.3 on 2024-03-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(default='https://res.cloudinary.com/dtq4d7luc/image/upload/v1710833246/default_gfiz3i.jpg', max_length=255),
        ),
    ]
