# Generated by Django 5.0.3 on 2024-03-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_post_caption_alter_post_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user_id',
        ),
        migrations.AddField(
            model_name='like',
            name='username',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='post_id',
            field=models.CharField(max_length=500),
        ),
    ]
