# Generated by Django 5.0.3 on 2024-03-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_like_user_id_like_username_alter_like_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='no_of_followed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='no_of_following',
            field=models.IntegerField(default=0),
        ),
    ]
