# Generated by Django 5.0.3 on 2024-03-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_profile_no_of_followed_profile_no_of_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followed_user_id',
            new_name='user',
        ),
    ]
