# Generated by Django 5.0.3 on 2024-04-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_comment_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='no_of_like',
            field=models.IntegerField(default=0),
        ),
    ]
